version: '3.8'
services:

  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - ${DB_PORT}
    volumes:
      - /var/lib/mongodb
    environment:
      MONGODB_ADMIN_USER: ${DB_NAME}
      MONGODB_ADMIN_PASS: ${DB_PASSWORD}
    command: mongod

  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./../:/var/www/
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
    - php-fpm
