controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
sign_in:
    path: /signin
    controller: App\Controller\SecurityController::signIn
    methods: POST